[package]
name = "sils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.lints.clippy]
pedantic = "warn"

[dependencies]
c2a-tobc-geox = { path = "../" }
c2a-dev-runtime = { git = "https://github.com/arkedge/c2a-core.git", tag = "v4.5.1" }

c2a-monazite-adc-bind = { git = "https://github.com/ut-issl/geox-cdh-monazite" }
c2a-monazite-adc-dev = { git = "https://github.com/ut-issl/geox-cdh-monazite" }
c2a-monazite-btmgr-bind = { git = "https://github.com/ut-issl/geox-cdh-monazite" }
c2a-monazite-btmgr-dev = { git = "https://github.com/ut-issl/geox-cdh-monazite" }
c2a-monazite-ccsds-bind = { git = "https://github.com/ut-issl/geox-cdh-monazite" }
c2a-monazite-ccsds-dev = { git = "https://github.com/ut-issl/geox-cdh-monazite" }
c2a-monazite-gpio-bind = { git = "https://github.com/ut-issl/geox-cdh-monazite" }
c2a-monazite-gpio-dev = { git = "https://github.com/ut-issl/geox-cdh-monazite" }
c2a-monazite-iflash-bind = { git = "https://github.com/ut-issl/geox-cdh-monazite" }
c2a-monazite-iflash-dev = { git = "https://github.com/ut-issl/geox-cdh-monazite" }
c2a-monazite-ramecc-bind = { git = "https://github.com/ut-issl/geox-cdh-monazite" }
c2a-monazite-ramecc-dev = { git = "https://github.com/ut-issl/geox-cdh-monazite" }
c2a-monazite-thermometer-bind = { git = "https://github.com/ut-issl/geox-cdh-monazite" }
c2a-monazite-thermometer-dev = { git = "https://github.com/ut-issl/geox-cdh-monazite" }
c2a-monazite-uart-bind = { git = "https://github.com/ut-issl/geox-cdh-monazite" }
c2a-monazite-uart-dev = { git = "https://github.com/ut-issl/geox-cdh-monazite" }
c2a-monazite-wdt-bind = { git = "https://github.com/ut-issl/geox-cdh-monazite" }
c2a-monazite-wdt-dev = { git = "https://github.com/ut-issl/geox-cdh-monazite" }

