#ifndef APP_REGISTRY_H_
#define APP_REGISTRY_H_
// こいつの自動生成がほしい．．．
typedef enum
{
  AR_NOP,

  // Driver Instances
  // Common
  // AR_DI_UART_EXAMPLE,
  // AR_DI_I2C_EXAMPLE,
  AR_DI_MOBC,
  AR_DI_MOBC_MST_PH,
  // AOCS
  AR_DI_MPU9250,
  AR_DI_RM3100,
  AR_DI_NANOSSOC_D60,
  AR_DI_STIM210,
  AR_DI_SAGITTA,
  AR_DI_OEM7600,
  AR_DI_MTQ_SEIREN,
  AR_DI_RW0003,
  AR_APP_MODULE_TEST_BENCH,  // 登録はしておくが、消しても良い
  // Power
  AR_DI_INA260,
  // CDH
  AR_DI_FM25V10,

  // Core
  AR_GSC_DISPATCHER,
  AR_RTC_DISPATCHER,
  AR_TLC_DISPATCHER_GS,
  AR_TLC_DISPATCHER_BC,
  AR_TLC_DISPATCHER_TLM,
  AR_EVENT_UTILITY,
  // AR_DBG_FLUSH_SCREEN,
  // AR_DBG_PRINT_TIMESTAMP,
  // AR_DBG_PRINT_CMD_STATUS,

  // User Defined
  // AOCS
  AR_APP_AOCS_MM_INITIAL,
  AR_APP_AOCS_MM_BDOT,
  AR_APP_AOCS_MM_SUN_POINTING,
  AR_APP_AOCS_MM_ROUGH_THREE_AXIS,
  AR_APP_AOCS_MM_FINE_THREE_AXIS,
  AR_APP_AOCS_MANAGER,
  // Control
  AR_APP_BDOT,
  AR_APP_SUN_POINTING,
  AR_APP_SUN_VEC_PROPAGATOR,
  AR_APP_THREE_AXIS_CONTROL_MTQ,
  AR_APP_THREE_AXIS_CONTROL_RW,
  AR_APP_UNLOADING,
  // Determination
  AR_APP_ROUGH_THREE_AXIS_DETERMINATION,
  AR_APP_FINE_THREE_AXIS_DETERMINATION,
  AR_APP_STT_GYRO_EKF,
  // Hardware Dependent
  AR_APP_AOCS_MTQ_SEIREN_CONTROLLER,
  AR_APP_AOCS_RW_CONTROLLER,
  AR_APP_MAG_SELECTOR,
  AR_APP_GYRO_SELECTOR,
  AR_APP_SUN_SENSOR_SELECTOR,
  AR_APP_STT_SELECTOR,
  AR_APP_GPSR_SELECTOR,
  AR_APP_MPU9250_FILTER,
  AR_APP_RM3100_FILTER,
  AR_APP_STIM210_FILTER,
  AR_APP_OEM7600_FILTER,
  AR_APP_RW0003_FILTER,
  AR_APP_SAGITTA_FILTER,
  AR_APP_NANOSSOC_D60_FILTER,
  // Orbit
  AR_APP_ORBIT_CALCULATOR,
  AR_APP_KEPLER_ORBIT_PROPAGATOR,
  AR_APP_SGP4_ORBIT_PROPAGATOR,
  AR_APP_GPSR_ORBIT_PROPAGATOR,
  // Environment
  AR_APP_TIME_SPACE_CALCULATOR,
  AR_APP_SUN_DIR_ECI_CALCULATOR,
  AR_APP_GEOMAG_ECI_CALCULATOR,
  // Target
  AR_APP_QUATERNION_INTERPOLATOR,
  AR_APP_TARGET_ATTITUDE_CALCULATOR,
  AR_APP_TARGET_ATTITUDE_FROM_ORBIT,
  // Power
  AR_APP_POWER_SWITCH_CONTROL,
  AR_APP_CURRENT_ANOMALY,
  // CDH
  AR_APP_NVM_MANAGER,
  AR_APP_NVM_PARTITION,
  AR_APP_NVM_PARAMETER,
  AR_APP_AOCS_DATA_RECORDER,
  // Thermal
  AR_APP_THERMO_SENSOR,
  AR_APP_TEMPERATURE_ANOMALY,
  // 最大数は80 (app_manager_params.hで設定)
} AR_APP_ID;

void AR_load_initial_settings(void);

#endif // APP_REGISTRY_H_
