#ifndef USER_DEFINED_SENSOR_NUMBER_H_
#define USER_DEFINED_SENSOR_NUMBER_H_

// Undefined
#undef NANOSSOC_D60_PARAMETERS_NUMBER_OF_MOUNTED_SENSOR

// Sun sensor
#define NANOSSOC_D60_PARAMETERS_NUMBER_OF_MOUNTED_SENSOR (4)  //!< Number of mounted sun sensor ( <= 6)

#endif // USER_DEFINED_SENSOR_NUMBER_H_
