name: labeler

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/labeler.yml
      - .github/labels.yml

jobs:
  labeler:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4

      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels.yml
          skip-delete: false
          dry-run: ${{ github.ref != 'refs/heads/main' }}
